### ISSUE TITLE
[Subtask]: Segment Compaction: part 2

### ISSUE THREAD

**Issue by small-turtle-1** [infiniflow/infinity#485]
### Parent Issue

[466](https://github.com/infiniflow/infinity/issues/466)

### Detail of Subtask

- [x] Add sql command for compaction to trigger it manually.
- [x] Fix bug of using deprecate segment in build index.
- [x] Create index for compacted segments.
- [x] Add more unit test and sql test.
