### ISSUE TITLE
[Feature Request]: HTTP API support

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/infinity#779]
### Describe the feature you'd like

Infinity needs HTTP API to support, detailed API design, please follow [HTTP API](https://github.com/infiniflow/infinity/blob/main/docs/references/http_api_reference.md)

- [x] Create database @chrysanthemum-boy 
- [x] Drop database @chrysanthemum-boy 
- [x] List databases
- [x] Show database
- [x] Create table @chrysanthemum-boy 
- [x] Drop table @chrysanthemum-boy 
- [x] List tables @chrysanthemum-boy 
- [x] Show table @chrysanthemum-boy 
- [x] Show table columns
- [x] List table indexes @morphes1995 
- [x] Create index #828  @morphes1995 
- [x] Drop index #828 @morphes1995 
- [x] Show index #851 @morphes1995 
- [x] Insert #858 
- [x] Delete #862
- [x] Update #865
- [x] Search #870 #874
- [x] Show Variable @Thomas134 
- [x] List segments of a table
- [x] Show segment #897 @morphes1995 
- [x] List blocks of a segment
- [x] Show specific block of segment #901 @morphes1995 
- [x] Import data #984

**Comment by JinHai-CN** [comment]
@770 List database

**Comment by JinHai-CN** [comment]
Duplicated with #786

**Comment by Thomas134** [comment]
Drop table/Show variables

**Comment by morphes1995** [comment]
I want try to implement Create index/Drop index/ Show index

**Comment by morphes1995** [comment]
i want to implement segment related interfaces
